[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# The verbosity level to use during tests.
verbosity = 3

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }

[fuzz]
# The amount of fuzz runs to perform for each fuzz test case. 
# Higher values gives more confidence in results at the cost of testing speed.
runs = 256

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
